// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-xfQT6RwuZiATjkAfk3EfgBEcpOAPs28',
    appId: '1:481117553195:web:aea557efc520573575606e',
    messagingSenderId: '481117553195',
    projectId: 'testapp-a1569',
    authDomain: 'testapp-a1569.firebaseapp.com',
    storageBucket: 'testapp-a1569.firebasestorage.app',
    measurementId: 'G-SSE39T0RSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-xfQT6RwuZiATjkAfk3EfgBEcpOAPs28',
    appId: '1:481117553195:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '481117553195',
    projectId: 'testapp-a1569',
    authDomain: 'testapp-a1569.firebaseapp.com',
    storageBucket: 'testapp-a1569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xfQT6RwuZiATjkAfk3EfgBEcpOAPs28',
    appId: '1:481117553195:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '481117553195',
    projectId: 'testapp-a1569',
    authDomain: 'testapp-a1569.firebaseapp.com',
    storageBucket: 'testapp-a1569.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
